#!/usr/bin/env python3
"""Generate shared laws, IG opinions and balance values without dependencies."""
import argparse
import json
from pathlib import Path
import struct
import sys

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))
from territorial_doctrine.model import RULES, DOCTRINES  # noqa: E402

HEADER = "# Generated by tools/generate.py from territorial_doctrine/rules.json.\n"


def icon(index: int) -> bytes:
    """A small original DDS emblem; no dependency on vanilla image paths."""
    size = 64
    colors = [(94, 131, 111), (168, 139, 82), (88, 129, 164), (153, 87, 81)]
    color = colors[index]
    pixels = bytearray()
    for y in range(size):
        for x in range(size):
            edge = 3 <= x <= 60 and 3 <= y <= 60 and (x < 6 or x > 57 or y < 6 or y > 57)
            pole = 17 <= x <= 20 and 14 <= y <= 50
            flag = 21 <= x <= 47 and 14 <= y <= 32
            stripe = flag and (y - 14) // 5 <= index
            r, g, b = (225, 215, 185) if edge or pole else color if stripe else (34, 38, 44)
            pixels.extend((r, g, b, 255))
    # DDS_HEADER, uncompressed RGBA, pitch = width * 4.
    header = struct.pack('<7I11I8I5I', 124, 0x100F, size, size, size * 4, 0, 0,
                         *([0] * 11), 32, 0x41, 0, 32,
                         0xFF, 0xFF00, 0xFF0000, 0xFF000000,
                         0x1000, 0, 0, 0, 0)
    return b'DDS ' + header + pixels


def outputs() -> dict[Path, bytes]:
    out: dict[Path, bytes] = {}

    def put(path: str, data: str | bytes):
        encoding = 'utf-8' if path.endswith('.json') else 'utf-8-sig'
        out[ROOT / 'mod' / path] = data.encode(encoding) if isinstance(data, str) else data

    put('common/law_groups/td_law_group.txt', HEADER + '''lawgroup_territorial_doctrine = {
    law_group_category = power_structure
    base_enactment_days = 90
    change_allowed_trigger = {
        td_can_legislate_trigger = yes
        NOT = { has_variable = td_doctrine_lock }
    }
}
''')
    laws = HEADER
    ideologies = HEADER
    scores = HEADER + 'td_base_scores_effect = {\n    every_interest_group = { set_variable = { name = td_score value = 0 } }\n'
    opinion = {-2: 'strongly_disapprove', -1: 'disapprove', 0: 'neutral',
               1: 'approve', 2: 'strongly_approve'}
    for i, doctrine in enumerate(DOCTRINES):
        image = f'gfx/interface/icons/td/{doctrine}.dds'
        put(image, icon(i))
        laws += f'''law_td_{doctrine} = {{
    group = lawgroup_territorial_doctrine
    icon = "{image}"
    progressiveness = {i * 10}
    can_enact = {{ td_can_legislate_trigger = yes }}
    on_enact = {{ td_doctrine_changed_effect = yes }}
    ai_enact_weight_modifier = {{ value = 0 }}
}}
'''
    for group, opinions in RULES['groups'].items():
        ideologies += f'ideology_td_{group} = {{\n    icon = "gfx/interface/icons/td/strategic_frontiers.dds"\n    lawgroup_territorial_doctrine = {{\n'
        for doctrine, value in zip(DOCTRINES, opinions):
            ideologies += f'        law_td_{doctrine} = {opinion[value]}\n'
        ideologies += '    }\n}\n'
        scores += f'    ig:ig_{group} = {{\n'
        for doctrine, value in zip(DOCTRINES, opinions):
            scores += f'''        if = {{
            limit = {{ owner = {{ has_law = law_type:law_td_{doctrine} }} }}
            set_variable = {{ name = td_score value = {value * 10} }}
        }}
'''
        scores += '    }\n'
    scores += '}\n'
    put('common/laws/td_laws.txt', laws)
    put('common/ideologies/td_ideologies.txt', ideologies)
    put('common/scripted_effects/td_base_scores.txt', scores)
    values = HEADER
    for doctrine, data in RULES['doctrines'].items():
        values += f'td_{doctrine}_multiplier = {data["cost_multiplier"]}\n'
    for key, value in RULES['bill'].items():
        values += f'td_bill_{key} = {value}\n'
    values += 'td_fast_months = 12\ntd_fallback_months = 6\n'
    put('common/script_values/td_constants.txt', values)
    policy = HEADER
    policy += '''td_power_category = {
    value = 0
    if = { limit = { OR = { has_law = law_type:law_autocracy has_law = law_type:law_single_party_state } } value = 1 }
    else_if = { limit = { OR = { has_law = law_type:law_census_suffrage has_law = law_type:law_universal_suffrage } } value = 2 }
}
td_government_category = {
    value = 0
    if = { limit = { has_law = law_type:law_monarchy } value = 1 }
    else_if = { limit = { OR = { has_law = law_type:law_presidential_republic has_law = law_type:law_parliamentary_republic } } value = 2 }
}
'''
    policy += 'td_reason_bonus = {\n    value = 0\n'
    for reason in RULES['reasons'].values():
        policy += f'    if = {{ limit = {{ var:td_reason = {reason["id"]} }}\n'
        for category, mapping in (('government', {'other': 0, 'monarchy': 1, 'republic': 2}), ('power', {'other': 0, 'autocracy': 1, 'democracy': 2})):
            for name, index in mapping.items():
                bonus = reason[category][name]
                if bonus:
                    policy += f'        if = {{ limit = {{ td_{category}_category = {index} }} add = {bonus} }}\n'
        policy += '    }\n'
    policy += '}\ntd_reason_cost_multiplier = {\n    value = 1\n'
    for reason in RULES['reasons'].values():
        policy += f'    if = {{ limit = {{ var:td_reason = {reason["id"]} }} value = {reason["cost_multiplier"]} }}\n'
    policy += '}\ntd_actor_cost_multiplier = {\n    value = 1\n'
    for regime in RULES['regimes'].values():
        policy += f'    if = {{ limit = {{ td_power_category = {regime["id"]} }} value = {regime["actor_administration_multiplier"]} }}\n'
    policy += '}\n'
    put('common/script_values/td_policy_values.txt', policy)
    cache = HEADER + '''# Country scope with PREV = state. Store literal values so extinct former
# owners do not erase the institutional cost of territory they lost.
td_store_power_on_prev_state_effect = {
'''
    for regime in RULES['regimes'].values():
        cache += f'''    if = {{
        limit = {{ td_power_category = {regime['id']} }}
        prev = {{
            set_variable = {{ name = td_live_power value = {regime['id']} }}
            set_variable = {{ name = td_live_diplomatic value = {regime['diplomatic_multiplier']} }}
            set_variable = {{ name = td_live_administration value = {regime['inherited_administration_multiplier']} }}
        }}
    }}
'''
    cache += '}\n'
    put('common/scripted_effects/td_regime_cache.txt', cache)
    modifiers = HEADER
    for doctrine, data in RULES['doctrines'].items():
        if data['focus_limit']:
            modifiers += f'''td_focus_{doctrine} = {{
    country_bureaucracy_add = -{data['bureaucracy']}
    country_authority_add = -{data['authority']}
}}
'''
    modifiers += '''td_project_cost = { country_bureaucracy_add = -1 }
td_pledge_fulfilled = { interest_group_approval_add = 2 }
td_pledge_broken = { interest_group_approval_add = -5 }
td_requires_admission = { state_disallow_incorporation = yes }
'''
    put('common/static_modifiers/td_modifiers.txt', modifiers)
    for language, label in [('english', 'en'), ('simp_chinese', 'zh')]:
        loc = f'l_{language}:\n'
        loc += ' lawgroup_territorial_doctrine:0 "' + ('国家领土原则' if label == 'zh' else 'National Territorial Doctrine') + '"\n'
        loc += ' lawgroup_territorial_doctrine_desc:0 "' + ('决定领土主张的依据与治理责任；不能自动取得主权或改变人口文化。' if label == 'zh' else 'Defines territorial claims and governance obligations. Does not grant sovereignty or change cultures.') + '"\n'
        for doctrine, data in RULES['doctrines'].items():
            title = data[label]
            desc = (f'重点区域上限 {data["focus_limit"]}；每区域行政力 {data["bureaucracy"]}、权威力 {data["authority"]}；等待 {data["wait_months"]} 月；宣称额外恶名 {data["infamy"]}；项目成本倍率 {data["cost_multiplier"]}。Alpha 场景只开放一个北非重点区域。'
                    if label == 'zh' else f'Focus limit {data["focus_limit"]}; bureaucracy {data["bureaucracy"]}, authority {data["authority"]} per focus; wait {data["wait_months"]} months; claim infamy +{data["infamy"]}; project cost x{data["cost_multiplier"]}. Alpha exposes one North African focus.')
            loc += f' law_td_{doctrine}:0 "{title}"\n law_td_{doctrine}_desc:0 "{desc}"\n'
            if data['focus_limit']:
                loc += f' td_focus_{doctrine}:0 "{title} — ' + ('北非重点区域' if label == 'zh' else 'North African Focus') + '"\n'
        for group in RULES['groups']:
            loc += f' ideology_td_{group}:0 "' + ('领土原则立场' if label == 'zh' else 'Territorial Doctrine Position') + '"\n'
            loc += f' ideology_td_{group}_desc:0 "' + ('此集团对四种领土原则的基础倾向。具体法案另计目标与承诺。' if label == 'zh' else 'Base positions on the four doctrines. Bills also account for target conditions and pledges.') + '"\n'
        put(f'localization/{language}/td_laws_l_{language}.yml', loc)
    metadata = {
        'name': 'Territorial Doctrine — 国家领土原则',
        'id': 'territorial_doctrine', 'version': RULES['version'],
        'game_id': 'victoria3', 'supported_game_version': '1.13.*',
        'short_description': 'Individual territorial admission and contextual justifications / 逐州领土接纳与体制理由',
        'tags': ['Gameplay', 'Politics'], 'relationships': [],
        'game_custom_data': {'multiplayer_synchronized': True}
    }
    put('.metadata/metadata.json', json.dumps(metadata, ensure_ascii=False, indent=2) + '\n')
    return out


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true', help='fail if generated assets are stale')
    args = parser.parse_args()
    stale = []
    for path, data in outputs().items():
        if args.check:
            if not path.exists() or path.read_bytes() != data:
                stale.append(str(path.relative_to(ROOT)))
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_bytes(data)
    if stale:
        print('Stale generated files:\n' + '\n'.join(stale), file=sys.stderr)
        return 1
    print('Generated assets are current.' if args.check else 'Generated laws, opinions, balance constants, localization and icons.')
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
